# https://github.com/gradle/actions/blob/main/docs/setup-gradle.md
name: Gradle Check and Build
on:
  push:
    branches: ["main", "dev"]
  # allow manual execution of the workflow while testing
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        default: "warning"
      tags:
        description: "Test scenario tags"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      #
      # setup java is not needed here?
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      #
      # setup gradle automatically caches dependencies
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          # https://stackoverflow.com/questions/30054911/how-to-determine-the-version-of-gradle
          # this should be updated automatically from dependabot
          gradle-version: 8.1.1
          # https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#github-dependency-graph-support
          # must separate pr and build for dependency graph
          dependency-graph: generate-and-submit
      - name: Check with Gradle Wrapper
        run: ./gradlew check
      - name: Build with Gradle Wrapper
        run: ./gradlew build
