# this action checks prs with new dependencies
#
# https://github.com/actions/dependency-review-action
# https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#integrating-the-dependency-review-action
# Please keep in mind that you need a GitHub Advanced Security license if you're running this action on private repositories.
#
# Usage with pull requests from public forked repositories
# contents: write permission is not available for any workflow that is triggered by a pull request submitted from a public forked repository.
#
# https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#usage-with-pull-requests-from-public-forked-repositories
#
name: Generate and save dependency graph on pr
on:
  pull_request:
    branches: ["dev"]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        default: "warning"
      tags:
        description: "Test scenario tags"
permissions:
  contents: read
jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      # generates the dependency graph for forked repos to check
      - name: Generate and save dependency graph
        uses: gradle/actions/dependency-submission@v3
        with:
          dependency-graph: generate-and-upload
