name: Dependency Review Vulnerability Check
on:
  pull_request:
    branches: [dev"]
  push:
    branches: ["dev"]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        default: "warning"
      tags:
        description: "Test scenario tags"
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      # dependency review after dependency submission (dep graph is generated)
      # requires a timeout to make sure the dep graph is generated and submitted
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
        with:
          retry-on-snapshot-warnings: true
          retry-on-snapshot-warnings-timeout: 600
