name: dependency-review
on:
  pull_request:
    branches: [dev"]
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      # dependency review after dependency submission (dep graph is generated)
      # requires a timeout to make sure the dep graph is generated
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
        with:
          retry-on-snapshot-warnings: true
          retry-on-snapshot-warnings-timeout: 600
