# https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle
name: Publish package to GitHub Packages Workflow
on:
  release:
    types: [created]
  workflow_dispatch: {}
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish package Job
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17.0.2"
          distribution: "temurin"
      - name: Setup Gradle Step
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.1.1
      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
