# https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle
name: Publish package to GitHub Packages Workflow
on:
  release:
    # types: [created]
    types: [published]
  workflow_dispatch: {}
jobs:
  # publish:
  #   runs-on: ubuntu-latest
  #   name: Publish package Job
  # permissions:
  #   contents: read
  #   packages: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-java@v4
  #       with:
  #         java-version: "17.0.2"
  #         distribution: "temurin"
  #     - name: Setup Gradle Step
  #       uses: gradle/actions/setup-gradle@v3
  #       with:
  #         gradle-version: 8.1.1
  #     - name: Publish package
  #       run: ./gradlew publish
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # https://medium.com/@shanemyrick/publishing-to-github-packages-with-gradle-and-github-actions-4ad842634c4e
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Publish release Job
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
      - name: Set up JDK Step
        uses: actions/setup-java@v4
        with:
          java-version: "17.0.2"
          distribution: "temurin"
      - name: Setup Gradle Step
        uses: gradle/actions/setup-gradle@v3
        # with:
        #   gradle-version: 8.1.1
        # - name: Publish artifact Step
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
        #   # If we split on '/' and take the 3rd value,
        #   # we can get the release name.
        #   run: |
        #     NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
        #     echo "New version: ${NEW_VERSION}"
        #     echo "Github username: ${GITHUB_ACTOR}"
        #     ./gradlew -Pversion=${NEW_VERSION} publish
      - name: Publish package Step
        run: ./gradlew publish --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
