# https://github.com/gradle/actions/blob/main/docs/setup-gradle.md
# we are separating the pr and push for the dependency graph
# https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#github-dependency-graph-support
name: Gradle Check and Build Workflow
on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
  # allow manual execution of the workflow while testing
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        default: "warning"
      tags:
        description: "Test scenario tags"
jobs:
  build-linux:
    name: Lint and Build on Linux Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources Step
        uses: actions/checkout@v4
      #
      # setup java
      - uses: actions/setup-java@v4
        name: Setup Java Step
        with:
          distribution: temurin
          java-version: 17.0.2
      #
      # setup gradle automatically caches dependencies
      - name: Setup Gradle Step
        uses: gradle/actions/setup-gradle@v3
        with:
          # https://stackoverflow.com/questions/30054911/how-to-determine-the-version-of-gradle
          # this should be updated automatically from dependabot
          # https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#github-dependency-graph-support
          gradle-version: 8.1.1
      - name: Check with Gradle Wrapper Step
        run: ./gradlew check
      - name: Build with Gradle Wrapper Step
        run: ./gradlew build
      - name: Publish pitest report Step
        run: ./gradlew pitest
      - name: Deploy Pitest to GitHub Pages Step
        uses: peaceiris/actions-gh-pages@v4
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/dev'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/reports/pitest
  build-windows:
    name: Lint and Build on Windows Job
    runs-on: windows-latest
    steps:
      - name: Checkout sources Step
        uses: actions/checkout@v4
      #
      # setup java
      - uses: actions/setup-java@v4
        name: Setup Java Step
        with:
          distribution: temurin
          java-version: 17.0.2
      #
      # setup gradle automatically caches dependencies
      - name: Setup Gradle Step
        uses: gradle/actions/setup-gradle@v3
        with:
          # https://stackoverflow.com/questions/30054911/how-to-determine-the-version-of-gradle
          # this should be updated automatically from dependabot
          # https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#github-dependency-graph-support
          gradle-version: 8.1.1
      - name: Check with Gradle Wrapper Step
        run: ./gradlew check
      - name: Build with Gradle Wrapper Step
        run: ./gradlew build
