# https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md
# https://stackoverflow.com/questions/74744498/github-pushing-to-protected-branches-with-fine-grained-token
# NOTE: requires a GitHub token with with admin rights to create protected tags
#
# Created a github app to allow this action to bypass branch protection rules for tags
# https://gonzalohirsch.com/blog/semantic-release-and-branch-protection-rules/
name: Release Workflow
run-name: ${{ github.actor }} is automatically releasing 🚀
on:
  push:
    branches:
      - main # or main
permissions:
  contents: read # for checkout
jobs:
  release:
    name: Release Job
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout Step
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # get all history for git tags
      # we don't need node
      - name: Setup Node.js Step
        uses: actions/setup-node@v4
        with:
          node-version: "22.0.0"
      # - name: Install dependencies Step
      #   run: npm clean-install --ignore-scripts
      # - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies Step
      #   run: npm audit signatures
      - name: Release Step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release@23.1.1
